### ISSUE TITLE
Read More link on LiveStyle alpha App redirects to discontinued Beta LiveStyle

### ISSUE THREAD

**Issue by geckoseo** [livestyle/app#1]
On this page:

http://livestyle.io/

A new generation live edit tool for CSS, LESS and SCSS. [Read More](http://livestyle.emmet.io/).

The Read More link takes one to the dead beta project page.

It might not be an issue as I guess you are not far from removing the old beta LiveStyle extension from Chrome and will be providing package control for the new Alpha version currently under development.

It is a bit confusing though.

**Comment by sergeche** [comment]
This is a temporary link for those who completely new to LiveStyle. Ful web-site is under development now

**Comment by geckoseo** [comment]
Thanks, I thought that might be the case but was just a heads up in case it was an oversight..

I'm very excited about the new versions, really looking forward to the public release.

**Comment by sergeche** [comment]
Glas you like it :) I’d really appreciate if you test new Remote View feature and give any feedback on it.

**Comment by geckoseo** [comment]
The very brief test I did resulted in the remote view site showing up with broken images and missing CSS, but that might be because my firewalls block access to the local files..

I'll test some more when I have a bit of time and send some proper feedback.
